### ISSUE TITLE
Consulo crashes immediately when attempting to open from unity by clicking on a script (Mac)

### ISSUE THREAD

**Issue by sfjohansson** [consulo/consulo-unity3d#112]
Here is the crash log:

[threadDump-20170802-121857.txt](https://github.com/consulo/consulo-unity3d/files/1200845/threadDump-20170802-121857.txt)

**Comment by VISTALL** [comment]
Hi. Can you add some information about OS, Unity version, etc.

Thanks

**Comment by sfjohansson** [comment]
Certainly: 
OS: Sierra 10.12.6 (16G29)
UNITY:  5.6.2p4

**Comment by VISTALL** [comment]
Consulo plugin for Unity Editor is installed ?

**Comment by sfjohansson** [comment]
yeah, UnityEditorConsuloPlugin5.3 seems to have been updated 11 July according to my hard drive

**Comment by VISTALL** [comment]
Can you add vm option (replace SOMEPATH by your path)

-XX:ErrorFile={SOMEPATH}/hs_err_pid_%p.log

add to file consulo[x64].vmoptions(in 'Consulo.app/Contents' on macOS).

And try to crash again

(then attach this crash file)

**Comment by sfjohansson** [comment]
also I just attempted to delete the unit plugin but it doesn't prompt to install it when I open/import project

**Comment by sfjohansson** [comment]
There we go: 

[consulo.txt](https://github.com/consulo/consulo-unity3d/files/1200958/consulo.txt)

Also, when it does not crash it complains about unity editor not being open
<img width="897" alt="screen shot 2017-08-04 at 17 04 16" src="https://user-images.githubusercontent.com/912814/28976883-9c305da0-7937-11e7-998c-94c0809585f1.png">

My unity installation is not in the standard folder, if that has an effect

**Comment by VISTALL** [comment]
We talking about?
* Unity -> Consulo

or

* Consulo -> Unity (last screenshot). You need Unity plugin for it (due limitation of Unity "API")

**Comment by sfjohansson** [comment]
Yes, crash when pressing on a script in unity and it attempt to open consulo (plugin is inside unity project)

So the last screen is when the plugin is in place and I click on the icon the unity icon inside consulo

**Comment by VISTALL** [comment]
Plugin validator should suggest plugin install on every project import (or re-import). Hm

**Comment by sfjohansson** [comment]
here is the log output when I import a project
[consulo_import.txt](https://github.com/consulo/consulo-unity3d/files/1200996/consulo_import.txt)

**Comment by VISTALL** [comment]
Can you re-import Unity project (right click on root project directory -> Re-import Unity Project)
Result must be like this
![](http://klikr.org/f1459f6d9ee62d945705442488ef.png)

**Comment by sfjohansson** [comment]
Just getting the last box with editor not responding

**Comment by VISTALL** [comment]
Can you import 

https://github.com/VISTALL/unity-2d-pong-game

this project, and check ?(idk for now why plugin info is not show)

**Comment by sfjohansson** [comment]
No luck, downloaded and when I import it I just get the popup for "editor not responding", here is the log: 
[consulo_import_pong.txt](https://github.com/consulo/consulo-unity3d/files/1202238/consulo_import_pong.txt)

**Comment by VISTALL** [comment]
It's strange

**Comment by VISTALL** [comment]
I fixed problem with plugin validation (it's not handled 5.6 version). Should works.

For now i'm not found crashing problem

Thanks

**Comment by sfjohansson** [comment]
It finally prompted for an update today...so yes the unity plugin updates is working now.. :)  Although the "Not Responding" promptly still shows up...so there seems to still be something with the "Connection" Let me know if there is anything I can try here.

..and lets see if those crashes stays away..I guess it might just be a result of things not working properly...

I can see this in the log
017-08-07 16:53:32,827 [ 216880]   WARN - ditor.UnityEditorCommunication - Connect to localhost:58933 [localhost/127.0.0.1] failed: Connection refused (Connection refused)

**Comment by VISTALL** [comment]
Unity plugin(for editor) installed?

**Comment by sfjohansson** [comment]
Yeah...looks like it...using unity 5.6.2p4

<img width="514" alt="screen shot 2017-08-08 at 19 40 35" src="https://user-images.githubusercontent.com/912814/29092774-601c3078-7c7f-11e7-8003-5b00f67ab2ad.png">

**Comment by VISTALL** [comment]
Try to reimport project if Editor opened(with same project).

**Comment by sfjohansson** [comment]
Did the re-import...so testing with 5.5 and the sample pong project it works...but not on 5.6

**Comment by VISTALL** [comment]
Hmmm!

**Comment by sfjohansson** [comment]
Here is the latest log file when I import project:

[consulo_sample_project_log.txt](https://github.com/consulo/consulo-unity3d/files/1209544/consulo_sample_project_log.txt)

**Comment by VISTALL** [comment]
Looks like, you have some problem with Unity plugin(for editor). It's very strange

**Comment by sfjohansson** [comment]
yeah..it seems to start with 5.6... tested now also with 2017 and the same result

**Comment by VISTALL** [comment]
Looks like - my API server is not binded (for communication with Consulo). 

Idk why.

**Comment by VISTALL** [comment]
They changed NUnit dependencies in 5.6+ unity. And now plugin can't loaded (due no dependency error)
Working on migration

**Comment by sfjohansson** [comment]
There we go..I'm glad that I'm not digging up completely unexplainable issues =O thanks for looking at  these issues so quickly! :)

**Comment by VISTALL** [comment]
Variant for 5.6 +(without NUnit for now) - should works(import)

[UnityEditorConsuloPlugin5.6.zip](https://github.com/consulo/consulo-unity3d/files/1209687/UnityEditorConsuloPlugin5.6.zip)

**Comment by sfjohansson** [comment]
Awesome...its working now... although I had to disable it as the connection pop ups inside unity breaks flow...I look forward to the update! 👍  :)

**Comment by VISTALL** [comment]
Pushed changes to master. But i NUnit support is disabled (for now i have no idea how return it)
